# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fae6d82f30cf6d8d842ec4de9d4d28df6c3142b23632cad5bd765d400ffed096615d299da93c942fde8b66c56777305244ff4d86a9090f382c8c65fc798cfbd4

test:
  secret_key_base: b010724046b23fced6b4346a969c0fe3fd0502c133b9148dbe6d1a2d29930685c81108adb2419c03dd6ed843f4f974a5c55950278ca87defbdda6a19556878ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
